export const GATES = [
  {
    name: "CCNOT",
    label: "CCX",
    title: "Toffoli",
    description: "Flips the target only when both control qubits are |1⟩.",
    family: "controlled",
    qubits: 3,
    shortcut: "",
  },
  {
    name: "H",
    label: "H",
    title: "Hadamard",
    description: "Turns a basis state into an equal superposition.",
    family: "superposition",
    qubits: 1,
    shortcut: "H",
  },
  {
    name: "X",
    label: "X",
    title: "Pauli X",
    description: "Flips |0⟩ to |1⟩ and |1⟩ to |0⟩.",
    family: "pauli",
    qubits: 1,
    shortcut: "X",
  },
  {
    name: "Y",
    label: "Y",
    title: "Pauli Y",
    description: "Rotates the qubit by π around the Y axis.",
    family: "pauli",
    qubits: 1,
    shortcut: "Y",
  },
  {
    name: "Z",
    label: "Z",
    title: "Pauli Z",
    description: "Flips the phase of the |1⟩ amplitude.",
    family: "pauli",
    qubits: 1,
    shortcut: "Z",
  },
  {
    name: "S",
    label: "S",
    title: "Phase S",
    description: "Adds a π/2 phase to the |1⟩ amplitude.",
    family: "phase",
    qubits: 1,
    shortcut: "S",
  },
  {
    name: "T",
    label: "T",
    title: "Phase T",
    description: "Adds a π/4 phase to the |1⟩ amplitude.",
    family: "phase",
    qubits: 1,
    shortcut: "T",
  },
  {
    name: "CNOT",
    label: "CX",
    title: "Controlled X",
    description: "Flips the target when the control is |1⟩.",
    family: "controlled",
    qubits: 2,
    shortcut: "",
  },
  {
    name: "CZ",
    label: "CZ",
    title: "Controlled Z",
    description: "Flips the phase when both qubits are |1⟩.",
    family: "controlled",
    qubits: 2,
    shortcut: "",
  },
  {
    name: "SWAP",
    label: "SW",
    title: "Swap",
    description: "Exchanges the states of two qubits.",
    family: "controlled",
    qubits: 2,
    shortcut: "",
  },
];
export function gateFamily(name: string) {
  return GATES.find((g) => g.name === name)?.family ?? "controlled";
}
